# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Snapshot deploy

on:
  push:
    branches:
      - 'main'
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Set current date as env variable
        run: echo "BUILD_START=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Build with maven
        run: mvn -B package --file pom.xml
      - name: Login to Docker Hub
        if: contains('refs/heads/2024.06.x refs/heads/main', github.ref) && github.event_name=='push' && success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the mir Docker images and push them
        if: contains('refs/heads/2024.06.x refs/heads/main', github.ref) && github.event_name=='push' && success()
        run: |
          docker build . --file Dockerfile --tag vzgreposis/cug:${GITHUB_REF_NAME} --tag vzgreposis/cug:${GITHUB_REF_NAME}-${BUILD_START}
          docker push vzgreposis/cug:${GITHUB_REF_NAME} 
          docker push vzgreposis/cug:${GITHUB_REF_NAME}-${BUILD_START}
